# Generated by Django 5.2.17 on 2026-10-02 15:15

import django.db.models.deletion
import spider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_filename', models.CharField(blank=True, max_length=200)),
                ('stored_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=spider.models.paper_blob_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('quote', models.TextField()),
                ('why', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='spider.savedpaper')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedpaper',
            index=models.Index(fields=['user', 'created_at'], name='spider_save_user_id_f323df_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedpaper',
            constraint=models.UniqueConstraint(fields=('user', 'stored_name'), name='unique_paper_blob_name'),
        ),
        migrations.AddIndex(
            model_name='savedhighlight',
            index=models.Index(fields=['paper', 'created_at'], name='spider_save_paper_i_47bbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedhighlight',
            index=models.Index(fields=['user', 'created_at'], name='spider_save_user_id_2de633_idx'),
        ),
    ]
